apiVersion: v1
kind: Service
metadata:
  name: customerdetail
  namespace: virtualcluster
spec:
  selector:
    app: vcluster
    release: virtualcluster
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  type: LoadBalancer

---
